volumes:
  postgres_data: {}

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    healthcheck:
      test: pg_isready -U postgres
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
